import type {
  CharacterDefinition,
  DialogueEntry,
  HotspotDefinition,
  HotspotItemDefinition,
  InventoryItemDefinition,
  Npc,
  Room,
  RoomId,
} from "./types";

const PLACEHOLDER_BACKGROUND_SRC = "/game-assets/background_to_replace.svg";
const PLACEHOLDER_CHARACTER_SRC = "/game-assets/character_to_replace.svg";

export const ROOM_BACKGROUND_BY_ID: Record<RoomId, string> = {
  apartment: "/game-assets/background_apartment.jpg",
  elevator: "/game-assets/background_elevator.jpg",
  rooftop: "/game-assets/background_rooftop.jpg",
  bar: "/game-assets/background_bar.jpg",
  pharmacy: "/game-assets/background_pharmacy.jpg",
  arcade: "/game-assets/background_arcades.jpg",
  store: "/game-assets/background_store.jpg",
  street: "/game-assets/background_street.jpg",
  alley: "/game-assets/background_alley.jpg",
  garage: "/game-assets/background_garage.jpg",
  restooutside: "/game-assets/background_resto_outside.jpg",
  restoinside: "/game-assets/background_resto_inside.jpg",
  motel: "/game-assets/background_motel.jpg",
  safehouse: PLACEHOLDER_BACKGROUND_SRC,
  cab: "/game-assets/background_cab.jpg",
};

export const CHARACTERS: CharacterDefinition[] = [
  {
    id: "lucy",
    name: "Lucy",
    description: "The one who starts the case and keeps her fear buried under a hard stare.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_lucy_serious.png",
      happy: "/game-assets/character_lucy_happy.png",
      sad: "/game-assets/character_lucy_sad.png",
      angry: "/game-assets/character_lucy_angry.png",
    },
  },
  {
    id: "thegambler",
    name: "The Gambler",
    description: "A bar regular who sells rumors without ever admitting which ones are true.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_the_gambler_serious.png",
      happy: "/game-assets/character_the_gambler_happy.png",
      angry: "/game-assets/character_the_gambler_angry.png",
      winner: "/game-assets/character_the_gambler_winner.png",
    },
  },
  {
    id: "doctor",
    name: "The Doctor",
    description: "A tired late-night pharmacist who knows when a receipt hides something uglier than medicine.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_the_doctor_serious.png",
      happy: "/game-assets/character_the_doctor_happy.png",
      laughing: "/game-assets/character_the_doctor_laughing.png",
    },
  },
  {
    id: "mysteriouskid",
    name: "Mysterious Kid",
    description: "The kind of witness who talks in riddles until the right trade loosens his tongue.",
    defaultEmotion: "happy",
    emotions: {
      happy: "/game-assets/character_mind_reader_happy.png",
      suspicious: "/game-assets/character_mind_reader_suspicious.png",
      angry: "/game-assets/character_mind_reader_angry.png",
      serious: "/game-assets/character_mind_reader_suspicious.png",
    },
  },
  {
    id: "rose",
    name: "Rose",
    description: "A sharp witness from the Red Light Block who notices which cars stop and who gets inside them.",
    defaultEmotion: "sensual",
    emotions: {
      sensual: "/game-assets/character_rose_sensual.png",
      serious: "/game-assets/character_rose_serious.png",
      thinking: "/game-assets/character_rose_thinking.png",
    },
  },
  {
    id: "pepe",
    name: "Pepe",
    description: "A street contact who reads territorial movement better than most people read weather.",
    defaultEmotion: "serious",
    emotions: {
      happy: "/game-assets/character_pepe_happy.png",
      serious: "/game-assets/character_pepe_serious.png",
      thinking: "/game-assets/character_pepe_thinking.png",
    },
  },
  {
    id: "bodyguard",
    name: "BodyGuard",
    description: "The wall in front of Big Boss. He only becomes human when nicotine is involved.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_bodyguard_serious.png",
      happy: "/game-assets/character_bodyguard_happy.png",
      laughing: "/game-assets/character_bodyguard_laughing.png",
      tired: "/game-assets/character_bodyguard_tired.png",
    },
  },
  {
    id: "bigboss",
    name: "Big Boss",
    description: "A polished crime boss who never says more than he thinks he can survive saying.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_big_boss_serious.png",
      happy: "/game-assets/character_big_boss_happy.png",
    },
  },
  {
    id: "nails",
    name: "Nails",
    description: "A weak link who has survived this long by panicking before anyone else does.",
    defaultEmotion: "worried",
    emotions: {
      serious: "/game-assets/character_nails_serious.png",
      thinking: "/game-assets/character_nails_thinking.png",
      worried: "/game-assets/character_nails_worried.png",
    },
  },
  {
    id: "jenny",
    name: "Jenny",
    description: "Late-shift store clerk. Sprite pending final art.",
    defaultEmotion: "serious",
    emotions: {
      serious: PLACEHOLDER_CHARACTER_SRC,
      happy: PLACEHOLDER_CHARACTER_SRC,
      thinking: PLACEHOLDER_CHARACTER_SRC,
    },
  },
  {
    id: "streetracer",
    name: "Street Racer",
    description: "Garage witness. Sprite pending final art.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_driver_serious.png",
      happy: "/game-assets/character_driver_happy.png",
      laughing: "/game-assets/character_driver_laughing.png",
    },
  },
  {
    id: "blondie",
    name: "Blondie",
    description: "The woman everybody moved around the city, and the one you are trying to reach before dawn.",
    defaultEmotion: "serious",
    emotions: {
      serious: "/game-assets/character_blondie_serious.png",
      happy: "/game-assets/character_blondie_happy.png",
      sad: "/game-assets/character_blondie_sad.png",
    },
  },
];

export const CHARACTER_BY_ID: Record<string, CharacterDefinition> = Object.fromEntries(
  CHARACTERS.map((character) => [character.id, character]),
);

export const STAGE_CHARACTER_ID = "lucy";
export const STAGE_CHARACTER_BY_ROOM: Partial<Record<RoomId, string>> = {
  apartment: "lucy",
  bar: "thegambler",
  pharmacy: "doctor",
  arcade: "mysteriouskid",
  store: "jenny",
  street: "rose",
  alley: "pepe",
  garage: "streetracer",
  restooutside: "bodyguard",
  restoinside: "bigboss",
  motel: "nails",
};

export const ROOMS: Record<RoomId, Room> = {
  apartment: {
    id: "apartment",
    name: "Apartment",
    description: "Your place. Lucy, the jacket, and the email are where the case begins.",
    exits: ["elevator"],
  },
  elevator: {
    id: "elevator",
    name: "Elevator",
    description: "The building's tired throat, carrying you toward the roof or the city.",
    exits: ["apartment", "rooftop", "street"],
  },
  rooftop: {
    id: "rooftop",
    name: "Rooftop",
    description: "Open air, wet concrete, and a city that looks cleaner from far away.",
    exits: ["elevator"],
  },
  bar: {
    id: "bar",
    name: "The Bar",
    description: "First real lead. Neon, smoke, and a room full of people pretending not to remember Blondie.",
    exits: ["apartment", "pharmacy", "arcade"],
  },
  pharmacy: {
    id: "pharmacy",
    name: "Pharmacy",
    description: "Cold shelves and the kind of fluorescent honesty nobody likes after midnight.",
    exits: ["bar", "store"],
  },
  arcade: {
    id: "arcade",
    name: "Arcade Room",
    description: "Static, cabinets, and a witness who talks like he is half-awake and fully dangerous.",
    exits: ["bar", "street", "garage"],
  },
  store: {
    id: "store",
    name: "The Store",
    description: "Late-night supplies, cheap lies, and Jenny behind the counter.",
    exits: ["pharmacy", "street", "restooutside"],
  },
  street: {
    id: "street",
    name: "Red Light Block",
    description: "Neon spill, street witnesses, and the vending machine Mysterious Kid keeps hinting at.",
    exits: ["arcade", "store", "alley"],
  },
  alley: {
    id: "alley",
    name: "Dark Alley",
    description: "Hidden movement, stacked crates, and the kind of silence that belongs to territorial people.",
    exits: ["street", "garage"],
  },
  garage: {
    id: "garage",
    name: "Underground Garage",
    description: "Concrete, oil, and a car that matters more than anyone wants to admit.",
    exits: ["arcade", "alley", "restooutside", "motel"],
  },
  restooutside: {
    id: "restooutside",
    name: "Italian Restaurant Exterior",
    description: "Warm light outside a place that exists to keep certain conversations off the street.",
    exits: ["store", "garage", "restoinside"],
  },
  restoinside: {
    id: "restoinside",
    name: "Italian Restaurant Interior",
    description: "Red velvet, hushed plates, and Big Boss in the center of the room like a threat with table service.",
    exits: ["restooutside"],
  },
  motel: {
    id: "motel",
    name: "Motel Neon",
    description: "A place where weak men hide until stronger ones come to collect.",
    exits: ["garage", "safehouse"],
  },
  safehouse: {
    id: "safehouse",
    name: "The Safehouse",
    description: "Last stop before dawn. The place the whole night has been trying not to name.",
    exits: ["motel"],
  },
  cab: {
    id: "cab",
    name: "Cab",
    description: "Rain on the windshield and a meter turning the night into numbers.",
    exits: ["bar", "store", "street", "garage", "restooutside", "motel"],
  },
};

export const ROOM_ORDER: RoomId[] = [
  "apartment",
  "elevator",
  "rooftop",
  "bar",
  "pharmacy",
  "arcade",
  "store",
  "street",
  "alley",
  "garage",
  "restooutside",
  "restoinside",
  "motel",
  "safehouse",
  "cab",
];

export const ROOM_MAP_LAYOUT: Record<RoomId, { x: number; y: number }> = {
  apartment: { x: 48, y: 22 },
  elevator: { x: 48, y: 22 },
  rooftop: { x: 48, y: 10 },
  bar: { x: 22, y: 35 },
  pharmacy: { x: 84, y: 72 },
  arcade: { x: 14, y: 66 },
  store: { x: 72, y: 55 },
  street: { x: 56, y: 42 },
  alley: { x: 35, y: 72 },
  garage: { x: 70, y: 88 },
  restooutside: { x: 82, y: 40 },
  restoinside: { x: 88, y: 28 },
  motel: { x: 90, y: 78 },
  safehouse: { x: 16, y: 86 },
  cab: { x: 50, y: 92 },
};

export const STAGE_HOTSPOTS_BY_ROOM: Partial<Record<RoomId, HotspotDefinition[]>> = {
  apartment: [
    {
      id: "apartment-jacket-pocket",
      label: "Jacket on Chair",
      x: 1660,
      y: 1135,
      width: 330,
      height: 505,
      inspectText: "The pocket feels empty now. Whatever Lucy left there is already in your hands.",
    },
    {
      id: "apartment-videogame-screen",
      label: "Videogame Screen",
      x: 545,
      y: 910,
      width: 335,
      height: 485,
      inspectText: "The game screen is frozen mid-scene, like somebody dropped real life on top of the pause button.",
    },
    {
      id: "apartment-computer-screen",
      label: "Computer Screen",
      x: 225,
      y: 875,
      width: 265,
      height: 600,
      inspectText: "The email window is still open. From a distance all you can read is that somebody wanted you moving fast.",
    },
    {
      id: "apartment-window-city",
      label: "Window and City",
      x: 1730,
      y: 175,
      width: 1300,
      height: 790,
      inspectText: "The city is doing what it always does: glowing just enough to hide what matters.",
    },
  ],
  elevator: [
    {
      id: "elevator-window-city",
      label: "Window and City",
      x: 464,
      y: 561,
      width: 298,
      height: 416,
      inspectText: "Distance makes the city look honest. Distance lies.",
    },
    {
      id: "elevator-neighbor-note",
      label: "Neighbor Note",
      x: 1128,
      y: 680,
      width: 195,
      height: 297,
      inspectText: "A taped note curls under the damp. Somebody needed the warning badly enough to leave it behind.",
    },
    {
      id: "elevator-call-button",
      label: "Call Button",
      x: 2556,
      y: 736,
      width: 470,
      height: 663,
      inspectText: "The call button glows like it is waiting to judge your next move.",
    },
  ],
  rooftop: [
    {
      id: "rooftop-edge-view",
      label: "Edge View",
      x: 900,
      y: 240,
      width: 980,
      height: 620,
      inspectText: "From up here the city looks almost quiet. That is how you know it is hiding something.",
    },
  ],
  bar: [
    {
      id: "bar-poster-wall",
      label: "Wall Poster",
      x: 1860,
      y: 340,
      width: 260,
      height: 400,
      inspectText: "A faded poster clings to the brick wall. Even the glue looks tired.",
    },
    {
      id: "bar-bottle-zone",
      label: "Bottle Zone",
      x: 2356,
      y: 330,
      width: 594,
      height: 250,
      inspectText: "Rows of bottles stare back like glass witnesses with perfect memory and no intention of helping.",
    },
    {
      id: "bar-under-table",
      label: "Under Table",
      x: 360,
      y: 1066,
      width: 490,
      height: 344,
      inspectText: "The dark space beneath the back table has been disturbed recently.",
    },
  ],
  pharmacy: [
    {
      id: "pharmacy-medicine-shelf-one",
      label: "Medicine Shelf I",
      x: 430,
      y: 220,
      width: 585,
      height: 1145,
      inspectText: "One shelf looks cleaner than it should. Something boxed disappeared recently.",
    },
    {
      id: "pharmacy-diploma",
      label: "Diploma",
      x: 1325,
      y: 945,
      width: 240,
      height: 180,
      inspectText: "The framed diploma says competent. The hour says exhausted.",
    },
    {
      id: "pharmacy-medicine-shelf-two",
      label: "Medicine Shelf II",
      x: 2065,
      y: 100,
      width: 450,
      height: 1280,
      inspectText: "This shelf keeps the controlled stuff close and the excuses closer.",
    },
  ],
  arcade: [
    {
      id: "arcade-counter-computer",
      label: "Counter Computer",
      x: 360,
      y: 340,
      width: 520,
      height: 360,
      inspectText: "The register log still glows on-screen, one more machine keeping a better timeline than the people in the room.",
    },
    {
      id: "arcade-machine-one",
      label: "Arcade Machine",
      x: 1080,
      y: 250,
      width: 460,
      height: 980,
      inspectText: "Old cabinet. Loud attract mode. Zero useful answers.",
    },
    {
      id: "arcade-machine-two",
      label: "Arcade Machine 2",
      x: 1770,
      y: 240,
      width: 500,
      height: 1010,
      inspectText: "The return slot rattles when you touch it. Somebody left value behind in a hurry.",
    },
  ],
  store: [
    {
      id: "store-counter",
      label: "Counter",
      x: 220,
      y: 360,
      width: 690,
      height: 780,
      inspectText: "The counter is cluttered with the usual late-night economy: smokes, receipts, and regret.",
    },
    {
      id: "store-ice-cream-fridge",
      label: "Ice Cream Freezer",
      x: 1440,
      y: 920,
      width: 420,
      height: 450,
      inspectText: "Frozen sugar. No answers.",
    },
    {
      id: "store-drinks-fridge",
      label: "Drinks Fridge",
      x: 2750,
      y: 260,
      width: 450,
      height: 1410,
      inspectText: "Rows of neon-colored cans promise energy, bad ideas, or both.",
    },
  ],
  street: [
    {
      id: "street-vending-machine",
      label: "Vending Machine",
      x: 485,
      y: 785,
      width: 295,
      height: 550,
      inspectText: "A vending machine humming under bad light. One slot is perfect for a token trade.",
    },
    {
      id: "street-alley-entrance",
      label: "Alley Entrance",
      x: 1825,
      y: 785,
      width: 95,
      height: 315,
      inspectText: "A narrow cut into the dark. Exactly the sort of place people vanish through.",
    },
    {
      id: "street-ramen-store",
      label: "Ramen Shop",
      x: 2485,
      y: 450,
      width: 750,
      height: 700,
      inspectText: "Warm broth, fogged glass, and not one person inside who wants your case.",
    },
  ],
  alley: [
    {
      id: "alley-crate-stack",
      label: "Crate Stack",
      x: 960,
      y: 760,
      width: 460,
      height: 420,
      inspectText: "The crate stack is half-collapsed. Something heavy and useful is wedged behind it.",
    },
    {
      id: "alley-dumpster",
      label: "Dumpster",
      x: 160,
      y: 640,
      width: 420,
      height: 520,
      inspectText: "The dumpster smells like old rain and worse decisions.",
    },
    {
      id: "alley-fire-escape",
      label: "Fire Escape",
      x: 2340,
      y: 180,
      width: 360,
      height: 700,
      inspectText: "A rusted ladder vanishes upward. Optional trouble, probably.",
    },
  ],
  garage: [
    {
      id: "garage-car",
      label: "Car License Plate",
      x: 55,
      y: 880,
      width: 1045,
      height: 520,
      inspectText: "The car sits ready to leave. The plate matters more than the paint job.",
    },
    {
      id: "garage-tool-bench",
      label: "Tool Bench",
      x: 1130,
      y: 950,
      width: 235,
      height: 215,
      inspectText: "The bench is crowded with tools and shortcuts.",
    },
    {
      id: "garage-license-plate-pile",
      label: "Plate Pile",
      x: 1790,
      y: 1010,
      width: 85,
      height: 85,
      inspectText: "Bent plates and shaved numbers. Too many ways to stop a car from being itself.",
    },
  ],
  restooutside: [
    {
      id: "restooutside-entrance-door",
      label: "Entrance Door",
      x: 1125,
      y: 505,
      width: 290,
      height: 720,
      inspectText: "The door looks welcoming right up until the BodyGuard notices you.",
    },
    {
      id: "restooutside-menu-board",
      label: "Menu Board",
      x: 1790,
      y: 1010,
      width: 285,
      height: 430,
      inspectText: "Expensive food, expensive silence.",
    },
    {
      id: "restooutside-delivery-bike",
      label: "Delivery Bike",
      x: 20,
      y: 840,
      width: 860,
      height: 790,
      inspectText: "A delivery bike cooling off in the rain. Nobody parked it here for the romance.",
    },
  ],
  motel: [
    {
      id: "motel-neon-sign",
      label: "Neon Sign",
      x: 320,
      y: 180,
      width: 860,
      height: 300,
      inspectText: "The sign flickers like it is trying to forget its own name.",
    },
    {
      id: "motel-room-door",
      label: "Room Door",
      x: 1860,
      y: 360,
      width: 460,
      height: 780,
      inspectText: "A cheap room door with enough scratches to count as a warning.",
    },
  ],
  safehouse: [
    {
      id: "safehouse-metal-door",
      label: "Metal Door",
      x: 1320,
      y: 260,
      width: 500,
      height: 980,
      inspectText: "The metal door is reinforced, ugly, and just soft enough around the frame to make leverage matter.",
    },
    {
      id: "safehouse-side-window",
      label: "Boarded Window",
      x: 560,
      y: 240,
      width: 360,
      height: 460,
      inspectText: "The window is boarded from inside. Whoever hid here expected company eventually.",
    },
  ],
};

export const NPCS: Npc[] = [
  { id: "lucy", name: "Lucy", schedule: [{ from: "22:00", to: "29:00", room: "apartment" }] },
  { id: "thegambler", name: "The Gambler", schedule: [{ from: "22:00", to: "29:00", room: "bar" }] },
  { id: "doctor", name: "The Doctor", schedule: [{ from: "22:00", to: "29:00", room: "pharmacy" }] },
  { id: "mysteriouskid", name: "Mysterious Kid", schedule: [{ from: "22:00", to: "29:00", room: "arcade" }] },
  { id: "jenny", name: "Jenny", schedule: [{ from: "22:00", to: "29:00", room: "store" }] },
  { id: "rose", name: "Rose", schedule: [{ from: "22:00", to: "29:00", room: "street" }] },
  { id: "pepe", name: "Pepe", schedule: [{ from: "22:00", to: "29:00", room: "alley" }] },
  { id: "streetracer", name: "Street Racer", schedule: [{ from: "22:00", to: "29:00", room: "garage" }] },
  { id: "bodyguard", name: "BodyGuard", schedule: [{ from: "22:00", to: "29:00", room: "restooutside" }] },
  { id: "bigboss", name: "Big Boss", schedule: [{ from: "22:00", to: "29:00", room: "restoinside" }] },
  { id: "nails", name: "Nails", schedule: [{ from: "22:00", to: "29:00", room: "motel" }] },
];

export const MAX_CHARACTER_CLUES_PER_NPC = 3;

export const CHARACTER_CLUE_PRIORITY_BY_NPC: Partial<Record<string, string[]>> = {
  lucy: ["bar_address_known", "lucy_warned_about_police", "lucy_blondie_was_running"],
  thegambler: [
    "gambler_confirms_blondie_was_here",
    "gambler_confirms_meeting_went_wrong",
    "gambler_points_to_arcade_room",
  ],
  doctor: ["doctor_confirms_medical_suspicion", "doctor_hints_at_sedation_or_control", "store_marked_on_map"],
  mysteriouskid: ["mysterious_kid_vague_lead", "future_energy_drink_hook", "garage_lead_discovered"],
  rose: ["rose_confirms_blondie_entered_a_car", "license_plate_note", "red_light_block_marked_on_map"],
  pepe: ["pepe_confirms_hidden_movement", "territorial_clue_obtained"],
  streetracer: ["plate_match_confirmed", "street_racer_identifies_car_as_nails", "motel_neon_address_known"],
  bigboss: ["knows_big_boss_connected", "knows_dirty_cop_connected", "nails_is_weak_link"],
  nails: ["safehouse_location_known"],
  jenny: ["jenny_small_but_useful_detail"],
};

export const CLUES: Record<string, string> = {
  bar_address_known: "Lucy's email points to The Bar at 14 Mercer Street.",
  lucy_warned_about_police: "Lucy said Blondie did not trust the police.",
  lucy_blondie_was_running: "Lucy believes Blondie was trying to stay ahead of someone.",
  building_neighbor_note: "The elevator note warns: 'Don't trust the night super.'",
  gambler_confirms_blondie_was_here: "The Gambler confirmed Blondie was at the Bar that night.",
  gambler_confirms_meeting_went_wrong: "The Gambler said Blondie's meeting at the Bar went wrong fast.",
  gambler_points_to_arcade_room: "The Gambler pointed you toward Mysterious Kid in the Arcade Room.",
  crumpled_receipt: "A crumpled Pharmacy receipt was hidden under Blondie's back table.",
  doctor_confirms_medical_suspicion: "The Doctor recognized the receipt and confirmed Blondie brushed against sedatives.",
  doctor_hints_at_sedation_or_control: "The Doctor thinks somebody may have used sedation or chemical control.",
  store_marked_on_map: "The Doctor mentioned Jenny's late-night store as the next practical stop.",
  mysterious_kid_vague_lead: "Mysterious Kid noticed Blondie moving through the night in a hurry.",
  future_energy_drink_hook: "Mysterious Kid hinted he would trade a real answer for the right drink.",
  has_arcade_timeline_clue: "The arcade counter log confirms Blondie passed through later than she should have.",
  red_light_block_marked_on_map: "The neon strip near the Red Light Block matters to this route.",
  rose_confirms_blondie_entered_a_car: "Rose saw Blondie get into a car instead of walking away from the block.",
  license_plate_note: "Rose gave you a handwritten note with the car's plate number.",
  pepe_confirms_hidden_movement: "Pepe confirmed people were moving someone through the back routes that night.",
  territorial_clue_obtained: "Pepe's read of the alley says the route belonged to a controlled transport chain.",
  garage_lead_discovered: "Mysterious Kid finally gave you the lead to the Underground Garage.",
  plate_match_confirmed: "The plate at the garage matches Rose's handwritten note.",
  street_racer_identifies_car_as_nails: "Street Racer says the car belongs to Nails.",
  motel_neon_address_known: "Street Racer gave you the Motel Neon address.",
  restaurant_exterior_marked_on_map: "Street Racer linked Big Boss to the Italian Restaurant front.",
  jenny_small_but_useful_detail: "Jenny confirmed who still buys cigarettes this late and who tips to stay invisible.",
  knows_big_boss_connected: "Big Boss admitted enough to confirm he sits inside the corruption chain.",
  knows_dirty_cop_connected: "Big Boss indirectly confirmed a dirty cop is part of the network around Blondie.",
  nails_is_weak_link: "Big Boss treated Nails like a liability, which makes him the weak link.",
  safehouse_location_known: "Nails cracked and gave you the Safehouse location.",
};

export const DIALOGUE: Record<string, DialogueEntry> = {};

export const ENDINGS = {
  solved: "You force the safehouse door and reach Blondie before dawn.",
  wrong: "The trail slips away while you chase the wrong angle.",
  late: "Too late. Dawn catches the case before you can reach Blondie.",
};

export const INVENTORY_ITEMS: InventoryItemDefinition[] = [
  {
    id: "blondie_photo",
    label: "Blondie Photo",
    image: "/game-assets/item_photo_blondie.png",
    description: "A worn photo of Blondie. Useful for getting people to stop pretending they do not recognize her.",
  },
  {
    id: "crumpled_receipt",
    label: "Pharmacy Receipt",
    image: "/game-assets/item_pharmacy_receipt.png",
    description: "A damp receipt from the Pharmacy, folded small enough to hide under Blondie's table.",
  },
  {
    id: "sedative_box",
    label: "Sedative Box",
    image: "/game-assets/item_cassette.png",
    description: "A placeholder item sprite for a boxed sedative. It still reads like evidence.",
  },
  {
    id: "arcade_token",
    label: "Arcade Token",
    image: "/game-assets/item_key.png",
    description: "A placeholder sprite for an arcade token, just enough metal to buy one more clue.",
  },
  {
    id: "cigarette_pack",
    label: "Cigarette Pack",
    image: "/game-assets/item_cigarrettes.png",
    description: "Exactly the kind of cheap peace offering a tired BodyGuard would respect.",
  },
  {
    id: "energizing_drink",
    label: "Energy Drink",
    image: "/game-assets/item_beer.png",
    description: "Placeholder art, real purpose: the only bribe Mysterious Kid seems interested in.",
  },
  {
    id: "license_plate_note",
    label: "Plate Note",
    image: "/game-assets/item_wallet.png",
    description: "Rose's handwritten note with the plate number Blondie disappeared into.",
  },
  {
    id: "steel_bar",
    label: "Steel Bar",
    image: "/game-assets/item_key.png",
    description: "Placeholder art for the length of steel that can force a final door.",
  },
  {
    id: "screwdriver",
    label: "Screwdriver",
    image: "/game-assets/item_cassette.png",
    description: "Placeholder art for a practical tool better suited to prying than asking politely.",
  },
];

export const INVENTORY_ITEM_BY_ID: Record<string, InventoryItemDefinition> = Object.fromEntries(
  INVENTORY_ITEMS.map((item) => [item.id, item]),
);

export const HOTSPOT_ITEMS: HotspotItemDefinition[] = [
  {
    hotspotId: "apartment-jacket-pocket",
    itemId: "blondie_photo",
    label: "Blondie Photo",
    image: "/game-assets/item_photo_blondie.png",
    description:
      "A photo of Blondie, worn at the corners from being handled too often. A useful face to carry through a city full of bad liars.",
  },
  {
    hotspotId: "bar-under-table",
    itemId: "crumpled_receipt",
    label: "Pharmacy Receipt",
    image: "/game-assets/item_pharmacy_receipt.png",
    description:
      "A damp Pharmacy receipt folded small enough to hide under Blondie's back table. The print is smudged, but the destination still lands like a real lead.",
    addClues: ["crumpled_receipt"],
    addFlags: ["pharmacy_marked_on_map"],
    pickupMessage: "You pocket the crumpled Pharmacy receipt from beneath Blondie's back table.",
  },
  {
    hotspotId: "pharmacy-medicine-shelf-one",
    itemId: "sedative_box",
    label: "Sedative Box",
    image: "/game-assets/item_cassette.png",
    description: "A boxed sedative from the shelf. Placeholder art, real implication.",
    pickupMessage: "You take the sedative box off the shelf before anyone can pretend it is ordinary.",
  },
  {
    hotspotId: "arcade-machine-two",
    itemId: "arcade_token",
    label: "Arcade Token",
    image: "/game-assets/item_key.png",
    description: "A lone token stuck in the return slot, waiting for one more trade.",
    pickupMessage: "You work the token free from the machine's return slot.",
  },
  {
    hotspotId: "store-counter",
    itemId: "cigarette_pack",
    label: "Cigarette Pack",
    image: "/game-assets/item_cigarrettes.png",
    description: "A pack of cigarettes that looks useful long before it looks healthy.",
    pickupMessage: "You pick up a cigarette pack off the counter and pay Jenny enough not to argue.",
  },
  {
    hotspotId: "alley-crate-stack",
    itemId: "steel_bar",
    label: "Steel Bar",
    image: "/game-assets/item_key.png",
    description: "A length of steel tucked behind the crate stack. Crude, heavy, and exactly the kind of thing a final door hates.",
    pickupMessage: "You drag the steel bar out from behind the crates and keep it.",
  },
  {
    hotspotId: "garage-tool-bench",
    itemId: "screwdriver",
    label: "Screwdriver",
    image: "/game-assets/item_cassette.png",
    description: "A practical tool from the bench. Placeholder art now, useful leverage later.",
    pickupMessage: "You pocket a screwdriver from the crowded tool bench.",
  },
];

export const HOTSPOT_ITEM_BY_ID: Record<string, HotspotItemDefinition> = Object.fromEntries(
  HOTSPOT_ITEMS.map((item) => [item.hotspotId, item]),
);
